development:
  adapter: postgresql
  encoding: unicode
  database: blog_1
  pool: 5
  timeout: 5000
  username: alexander
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  timeout: 5000
  username: alexander
  password: